### ISSUE TITLE
Celery 5 support

### ISSUE THREAD

**Issue by aarongilman** [ovh/celery-dyrygent#23]
This is a great package and really helped me with automating large celery workflows. I recently updated my app to use Celery 5 and had continued to use this package without noticing any issues but started to debug some of the tasks this week and noticed this was only built for Celery 4. I haven't noticed anything obvious in terms of incompatibility but figured I would ask you first in the event you had an answer. So, two questions:

1. Do you plan to upgrade to Celery 5/add support? 
2. If not, is there anything that sticks out within this package that would not be compatible with Celery 5? I have looked through everything and can't seem to see anything that would cause any issues. 

I would prefer to keep using this if possible so wanted to see if I should fork and make any changes so I could use it with Celery 5 OR remove the package completely and try to go another route.

Thank you in advance and appreciate the good work!

**Comment by brabiega** [comment]
Hello,

The only reason why celery5 is not stated as supported is - I never battle tested such combination.
AFAIR when dyrygent was developed there was no celery 5 :octocat: (or there was but in very early revisions)
Since I've deployed dyrygent in my environment all the problems with celery are gone thus I never had any reason to upgrade...

I don't see any obvious obstacles in running celery5 with dyrygent.
However it would be reasonable to at least include celery5, py38+ in tests (tox) and update requirements.
I'll see what I can do do about it, but I'm a bit short on time right now :baby:

**Comment by brabiega** [comment]
I've removed some dust and I managed to successfully run integration tests against celery v5.2.7.
That's a good sign.

**Comment by aarongilman** [comment]
Thank you so much!  I understand time is a precious resource and appreciate you taking a stab at it when you can.

**Comment by lukaszgomulka** [comment]
Support for celery 5 already on master.
